/*
 * tracker_server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateTaskInput {
    #[serde(
        rename = "id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub id: Option<Option<String>>,
    #[serde(rename = "summary")]
    pub summary: String,
}

impl CreateTaskInput {
    pub fn new(summary: String) -> CreateTaskInput {
        CreateTaskInput { id: None, summary }
    }
}
